# Generated by Django 3.2.7 on 2021-10-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('Valor', models.IntegerField(verbose_name='Valor')),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rareza', models.CharField(max_length=15, verbose_name='Rareza')),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=25, verbose_name='Nickname')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='coleccionHeroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrega1.hero')),
                ('ID_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrega1.player')),
            ],
        ),
    ]
