# Generated by Django 3.2.9 on 2021-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('jugada1', models.CharField(max_length=255)),
                ('jugada2', models.CharField(max_length=255)),
                ('ganador', models.CharField(max_length=255)),
            ],
        ),
    ]
