# Generated by Django 3.2.7 on 2021-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20211005_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relator',
            name='correo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Correo Electronico'),
        ),
    ]
